#!/bin/sh
# shellcheck disable=SC2034 # Allow unused variables
set -eu

useColor() {
	if [ "${FORCE_COLOR:-"false"}" = "true" ] || [ -t 1 ] && [ -t 2 ] && [ "${USE_COLOR:-"true"}" = "true" ]; then
		return 0
	else
		return 1
	fi
}

if useColor; then USE_COLOR=true; else unset USE_COLOR; fi


T_ESC="${USE_COLOR+"\033["}"

###   -----   RESET FORMAT OR COLOR   -----   ###
TR="${T_ESC}${USE_COLOR+"0m"}"
TR_F="${T_ESC}${USE_COLOR+"39m"}"               TR_B="${T_ESC}${USE_COLOR+"49m"}"

# --- These escape codes are not always supported --- #
# TR_BOLD="${T_ESC}${USE_COLOR+"21m"}"            TR_BLINK="${T_ESC}${USE_COLOR+"25m"}"
# TR_DIM="${T_ESC}${USE_COLOR+"22m"}"             TR_REVERSE="${T_ESC}${USE_COLOR+"27m"}"
# TR_UNDERLINE="${T_ESC}${USE_COLOR+"24m"}"       TR_HIDDEN="${T_ESC}${USE_COLOR+"28m"}"

###   -----   TEXT FORMATTING   -----   ###
T_BOLD="${T_ESC}${USE_COLOR+"1m"}";             T_BLINK="${T_ESC}${USE_COLOR+"5m"}";
T_DIM="${T_ESC}${USE_COLOR+"2m"}";              T_REVERSE="${T_ESC}${USE_COLOR+"7m"}";
T_UNDERLINE="${T_ESC}${USE_COLOR+"4m"}";        T_HIDDEN="${T_ESC}${USE_COLOR+"8m"}";

###   -----   FOREGROUND COLORS   -----   ###
TF_BLACK="${T_ESC}${USE_COLOR+"30m"}";          TF_WHITE="${T_ESC}${USE_COLOR+"97m"}";
TF_RED="${T_ESC}${USE_COLOR+"31m"}";            TF_LIGHT_RED="${T_ESC}${USE_COLOR+"91m"}";
TF_GREEN="${T_ESC}${USE_COLOR+"32m"}";          TF_LIGHT_GREEN="${T_ESC}${USE_COLOR+"92m"}";
TF_YELLOW="${T_ESC}${USE_COLOR+"33m"}";         TF_LIGHT_YELLOW="${T_ESC}${USE_COLOR+"93m"}";
TF_BLUE="${T_ESC}${USE_COLOR+"34m"}";           TF_LIGHT_BLUE="${T_ESC}${USE_COLOR+"94m"}";
TF_MAGENTA="${T_ESC}${USE_COLOR+"35m"}";        TF_LIGHT_MAGENTA="${T_ESC}${USE_COLOR+"95m"}";
TF_CYAN="${T_ESC}${USE_COLOR+"36m"}";           TF_LIGHT_CYAN="${T_ESC}${USE_COLOR+"96m"}";
TF_DARK_GRAY="${T_ESC}${USE_COLOR+"90m"}";      TF_LIGHT_GRAY="${T_ESC}${USE_COLOR+"37m"}";

###   -----   BACKGROUND COLORS   -----   ###
TB_BLACK="${T_ESC}${USE_COLOR+"40m"}"           TB_WHITE="${T_ESC}${USE_COLOR+"107m"}"
TB_RED="${T_ESC}${USE_COLOR+"41m"}"             TB_LIGHT_RED="${T_ESC}${USE_COLOR+"101m"}"
TB_GREEN="${T_ESC}${USE_COLOR+"42m"}"           TB_LIGHT_GREEN="${T_ESC}${USE_COLOR+"102m"}"
TB_YELLOW="${T_ESC}${USE_COLOR+"43m"}"          TB_LIGHT_YELLOW="${T_ESC}${USE_COLOR+"103m"}"
TB_BLUE="${T_ESC}${USE_COLOR+"44m"}"            TB_LIGHT_BLUE="${T_ESC}${USE_COLOR+"104m"}"
TB_MAGENTA="${T_ESC}${USE_COLOR+"45m"}"         TB_LIGHT_MAGENTA="${T_ESC}${USE_COLOR+"105m"}"
TB_CYAN="${T_ESC}${USE_COLOR+"46m"}"            TB_LIGHT_CYAN="${T_ESC}${USE_COLOR+"106m"}"
TB_DARK_GRAY="${T_ESC}${USE_COLOR+"100m"}"      TB_LIGHT_GRAY="${T_ESC}${USE_COLOR+"47m"}"


# Helper functions for echoing text.
# These auto resets formating
stderr() {
	printf "%b\n${TR}" "$@" 1>&2
}
print() {
	printf "%b\n${TR}" "$@"
}




print "--- ${T_BOLD}Formatting${TR} ---"

print "${TR}${T_BOLD}BOLD${TR} reset"
print "${TR}${T_DIM}DIM${TR} reset"
print "${TR}${T_UNDERLINE}UNDERLINE${TR} reset"
print "${TR}${T_BLINK}BLINK${TR} reset"
print "${TR}${T_REVERSE}REVERSE${TR} reset"
print "${TR}${T_HIDDEN}HIDDEN${TR} reset"


print "\n\n--- ${T_BOLD}Colors${TR} ---"

print "${TF_BLACK}black${TR}\t\treset"
print "${TF_RED}red${TR}\t\treset"
print "${TF_GREEN}green${TR}\t\treset"
print "${TF_YELLOW}yellow${TR}\t\treset"
print "${TF_BLUE}blue${TR}\t\treset"
print "${TF_MAGENTA}magenta${TR}\t\treset"
print "${TF_CYAN}cyan${TR}\t\treset"
print "${TF_LIGHT_GRAY}light_gray${TR}\treset"
print "${TF_DARK_GRAY}dark_gray${TR}\treset"
print "${TF_LIGHT_RED}light_red${TR}\treset"
print "${TF_LIGHT_GREEN}light_green${TR}\treset"
print "${TF_LIGHT_YELLOW}light_yellow${TR}\treset"
print "${TF_LIGHT_BLUE}light_blue${TR}\treset"
print "${TF_LIGHT_MAGENTA}light_magenta${TR}\treset"
print "${TF_LIGHT_CYAN}light_cyan${TR}\treset"
print "${TF_WHITE}white${TR}\t\treset"


print "\n\n--- ${T_BOLD}Background${TR} ---"

print "${TB_BLACK}black${TR}\t\treset"
print "${TB_RED}red${TR}\t\treset"
print "${TB_GREEN}green${TR}\t\treset"
print "${TB_YELLOW}yellow${TR}\t\treset"
print "${TB_BLUE}blue${TR}\t\treset"
print "${TB_MAGENTA}magenta${TR}\t\treset"
print "${TB_CYAN}cyan${TR}\t\treset"
print "${TB_LIGHT_GRAY}light_gray${TR}\treset"
print "${TB_DARK_GRAY}dark_gray${TR}\treset"
print "${TB_LIGHT_RED}light_red${TR}\treset"
print "${TB_LIGHT_GREEN}light_green${TR}\treset"
print "${TB_LIGHT_YELLOW}light_yellow${TR}\treset"
print "${TB_LIGHT_BLUE}light_blue${TR}\treset"
print "${TB_LIGHT_MAGENTA}light_magenta${TR}\treset"
print "${TB_LIGHT_CYAN}light_cyan${TR}\treset"
print "${TB_WHITE}white${TR}\t\treset"


print "\n\n--- ${T_BOLD}Combinations${TR} ---"
print "${T_BOLD}${TF_RED}Bold red${TR}"
print "${T_DIM}${TF_GREEN}Dim green${TR}"
print "${T_UNDERLINE}${TF_YELLOW}Underline yellow${TR}"
print "${T_BLINK}${TF_MAGENTA}Blink magenta${TR}"
print "${T_REVERSE}${TF_CYAN}Reverse cyan${TR}"
print "${TB_LIGHT_GRAY}${TF_BLUE}BLue on light_gray${TR}"
