#!/bin/sh
# shellcheck disable=SC2034 # Allow unused variables

# Strict shell execution commented out.
# People sourcing this file may not expect/want strict shell exection.
# See: https://unix.stackexchange.com/a/595254
# set -eu

isColorSupported() {
	if [ "${FORCE_COLOR:-"false"}" = "true" ] || [ -t 1 ] && [ -t 2 ] && [ "${USE_COLOR:-"true"}" = "true" ]; then
		return 0
	else
		return 1
	fi
}

if isColorSupported; then USE_COLOR=true; else unset USE_COLOR; fi

# Need to put this in variable on its own.
# It cannot be directly in parameter expansion below because then it won't work in bash and ksh
# ¯\_(ツ)_/¯
_T_ESC_="\033["
T_ESC="${USE_COLOR+"$_T_ESC_"}"

###   -----   RESET FORMAT OR COLOR   -----   ###
TR="${T_ESC}${USE_COLOR+"0m"}"
TR_F="${T_ESC}${USE_COLOR+"39m"}"               TR_B="${T_ESC}${USE_COLOR+"49m"}"

# --- These escape codes are not always supported --- #
# TR_BOLD="${T_ESC}${USE_COLOR+"21m"}"            TR_BLINK="${T_ESC}${USE_COLOR+"25m"}"
# TR_DIM="${T_ESC}${USE_COLOR+"22m"}"             TR_REVERSE="${T_ESC}${USE_COLOR+"27m"}"
# TR_ITALIC="${T_ESC}${USE_COLOR+"23m"}"          TR_HIDDEN="${T_ESC}${USE_COLOR+"28m"}"
# TR_UNDERLINE="${T_ESC}${USE_COLOR+"24m"}"       TR_STRIKE="${T_ESC}${USE_COLOR+"29m"}"

###   -----   TEXT FORMATTING   -----   ###
T_BOLD="${T_ESC}${USE_COLOR+"1m"}";             T_BLINK="${T_ESC}${USE_COLOR+"5m"}";
T_DIM="${T_ESC}${USE_COLOR+"2m"}";              T_REVERSE="${T_ESC}${USE_COLOR+"7m"}";
T_ITALIC="${T_ESC}${USE_COLOR+"3m"}"            T_HIDDEN="${T_ESC}${USE_COLOR+"8m"}";
T_UNDERLINE="${T_ESC}${USE_COLOR+"4m"}";        T_STRIKE="${T_ESC}${USE_COLOR+"9m"}"

###   -----   FOREGROUND COLORS   -----   ###
TF_BLACK="${T_ESC}${USE_COLOR+"30m"}";          TF_WHITE="${T_ESC}${USE_COLOR+"97m"}";
TF_RED="${T_ESC}${USE_COLOR+"31m"}";            TF_BRIGHT_RED="${T_ESC}${USE_COLOR+"91m"}";
TF_GREEN="${T_ESC}${USE_COLOR+"32m"}";          TF_BRIGHT_GREEN="${T_ESC}${USE_COLOR+"92m"}";
TF_YELLOW="${T_ESC}${USE_COLOR+"33m"}";         TF_BRIGHT_YELLOW="${T_ESC}${USE_COLOR+"93m"}";
TF_BLUE="${T_ESC}${USE_COLOR+"34m"}";           TF_BRIGHT_BLUE="${T_ESC}${USE_COLOR+"94m"}";
TF_MAGENTA="${T_ESC}${USE_COLOR+"35m"}";        TF_BRIGHT_MAGENTA="${T_ESC}${USE_COLOR+"95m"}";
TF_CYAN="${T_ESC}${USE_COLOR+"36m"}";           TF_BRIGHT_CYAN="${T_ESC}${USE_COLOR+"96m"}";
TF_DARK_GRAY="${T_ESC}${USE_COLOR+"90m"}";      TF_BRIGHT_GRAY="${T_ESC}${USE_COLOR+"37m"}";

###   -----   BACKGROUND COLORS   -----   ###
TB_BLACK="${T_ESC}${USE_COLOR+"40m"}"           TB_WHITE="${T_ESC}${USE_COLOR+"107m"}"
TB_RED="${T_ESC}${USE_COLOR+"41m"}"             TB_BRIGHT_RED="${T_ESC}${USE_COLOR+"101m"}"
TB_GREEN="${T_ESC}${USE_COLOR+"42m"}"           TB_BRIGHT_GREEN="${T_ESC}${USE_COLOR+"102m"}"
TB_YELLOW="${T_ESC}${USE_COLOR+"43m"}"          TB_BRIGHT_YELLOW="${T_ESC}${USE_COLOR+"103m"}"
TB_BLUE="${T_ESC}${USE_COLOR+"44m"}"            TB_BRIGHT_BLUE="${T_ESC}${USE_COLOR+"104m"}"
TB_MAGENTA="${T_ESC}${USE_COLOR+"45m"}"         TB_BRIGHT_MAGENTA="${T_ESC}${USE_COLOR+"105m"}"
TB_CYAN="${T_ESC}${USE_COLOR+"46m"}"            TB_BRIGHT_CYAN="${T_ESC}${USE_COLOR+"106m"}"
TB_DARK_GRAY="${T_ESC}${USE_COLOR+"100m"}"      TB_BRIGHT_GRAY="${T_ESC}${USE_COLOR+"47m"}"


# Helper functions for echoing/printing text.
# printf is fully posix compliant and is generally safer than echo.
# These auto resets formating
stderr() {
	printf "%b\n${TR}" "$@" 1>&2
}
print() {
	printf "%b\n${TR}" "$@"
}
